import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
      <nav className="fixed w-full bg-black h-16 px-4 flex text-white z-50 align-middle">
          <div className="text-lg my-auto">
              nextChess
          </div>
      </nav>
      <div className={"pt-20"} />
      {children}
      </body>
    </html>
  )
}
